### ISSUE TITLE
Works from CLI but doesn't work from web

### ISSUE THREAD

**Issue by immortalsantee** [saeedvaziry/laravel-async#4]
```
class Foo extends Command {
 public function handle(): void
    {
        AsyncHandler::dispatch(static function () {
             SMPushNotification::smSend();
         });
     }
}
```

`php artisan foo` works

but

```
class UserController extends Controller {
   public function index()
    {
       AsyncHandler::dispatch(static function () {
             SMPushNotification::smSend();
         });
    }
}
```

(new UserController)->index(); doesn't work.

Is there anything i am missing here?

**Comment by saeedvaziry** [comment]
Looks like a bug!

The reason is, When running with webserver it cannot find the executable PHP.

So we should define the path of the executable in the config files.

Will work on in the weekend.

**Comment by saeedvaziry** [comment]
Fixed.

You can now update

```
composer update saeedvaziry/laravel-async
```

Also check here

https://github.com/saeedvaziry/laravel-async?tab=readme-ov-file#configuration

**Comment by immortalsantee** [comment]
Thanks @saeedvaziry.
